# Generated by Django 5.1.2 on 2024-10-31 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iana_Spotify', '0002_cancionsimilar_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancionsimilar',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cancionsimilar',
            name='artista_similar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cancionsimilar',
            name='cancion_favorita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones_similares', to='Iana_Spotify.cancionfavorita'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cancionfavorita',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título de la Canción Favorita'),
        ),
        migrations.AlterField(
            model_name='cancionsimilar',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones_similares', to='Iana_Spotify.artista'),
        ),
    ]
