# Generated by Django 5.1.2 on 2024-10-31 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iana_Spotify', '0003_remove_cancionsimilar_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancionsimilar',
            name='cancion_favorita',
        ),
    ]
