# Generated by Django 5.1.2 on 2024-10-31 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iana_Spotify', '0005_alter_artista_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancionsimilar',
            name='artista_similar',
        ),
        migrations.AddField(
            model_name='cancionsimilar',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cancionfavorita',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cancionsimilar',
            name='artista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Iana_Spotify.artista'),
        ),
    ]
