# Generated by Django 5.1.2 on 2024-10-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iana_Spotify', '0007_alter_artista_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancionsimilar',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cancionsimilar',
            name='artista_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones_similares', to='Iana_Spotify.artista'),
        ),
    ]
